---
title: "Projeto"
author: "cassiofpa"
date: "2021-07-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introdução

- É incontestável o papel das estatísticas públicas para a formulação e avaliação de políticas públicas. - - Há muitas bases de dados disponíveis - Dados Abertos
- Geralmente são acessíveis para um público especializado
- Não há uma interface que facilite a tabulação dos dados


## Justificativa para escolha do tema

- É importante que todos tenham acesso às estatísticas públicas
- É importante que todos possam fazer a própria tabulação
- Há a necessidade de instrumentos que facilitem o acesso e proporcionem uma interpretação adequada destas estatísticas. 

## Objetivo geral e objetivos específicos

- gerar um método simplificado para tabulações da PNAD-contínua 
- explorar os resultados dando ênfase às medidas e incertezas em tabelas e gráficos.


## Quais as etapas do projeto?

1. Entender o que é uma pesquisa amostral   
3. Conhecer a Pesquisa Nacional por amostra de domicílios (PNAD Contínua)
4. Conhecer e aplicar as melhores técnias e Ciências de Dados:
    - Programação em R (Avançada)
    - Visualização de dados
    - Geração automática de documentos
    - uso do Git
5. Gerar tabulações com dados da PNAD contínua;
6. Selecionar formas gráficas para analisar e interpretar os resultados;
7. Construir uma biblioteca em R para gerar tabulações e gráficos com dados da PNAD-contínua.



## Resultados e impactos esperados

- Possibilitar que qualquer usuário com conhecimento básico de R  gerar tabulações e gráficos com dados da PNADc
    - Uma biblioteca em R que facilite as tabulações da PNADc
    - Tutorial para greração das tabulações e interpretação dos resultados



## Projeto Original 

Para visualizar o Projeto Original use o link  [Projeto Completo](Projeto_completo.html).